#page title
page_title                                : Aloud! - Background & Offline TTS | AppAppWorks                                          # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 852033350                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).
ios_app_country                           : us                                        # Required outside USA. Enter 2 letter country code as in https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2

appstore_link                             :                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.
presskit_download_link                    :                                          # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : /assets/appicon.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : Aloud! - Background & Offline TTS                                        # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 : Free                                          # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : Hear PDF, eBooks & Web Pages

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : AppAppWorks                                
your_link                                 : https://appappworks.com                     
your_city                                 : Hong Kong                                
email_address                             : info@appappworks.com
linkedin_username                         :                                           
linkedin_company                          : 
facebook_username                         : appappworks                                          
instagram_username                        : 
twitter_username                          : appappworks
github_username                           : 
youtube_username                          :
mastodon_link                             : 



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Background & Offline Playback
    description                           : Listen anywhere, no signal required. Aloud! works completely offline, giving you the freedom to read on your terms.
    fontawesome_icon_name                 : wifi

  - title                                 : Multi-format Support
    description                           : From PDFs and ePubs to webpages, Aloud! handles it all. Import documents from the web, your files, or other apps instantly.
    fontawesome_icon_name                 : file

  - title                                 : Multiple Languages, Multiple Voices
    description                           : Listen to the world. Aloud! supports dozens of languages, each with a selection of unique voices. Find the perfect voice to bring any text to life.
    fontawesome_icon_name                 : language    

  - title                                 : Control Reading Progress, Speed and Pitch
    description                           : Your reading, your rules. Easily track your progress, skip to any section, and fine-tune the reading speed and pitch to match your preference.
    fontawesome_icon_name                 : play-circle

  - title                                 : Save Texts and Progress
    description                           : Never lose your place. Aloud! automatically saves your articles and progress, so you can stop and resume anytime.
    fontawesome_icon_name                 : save



# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#f5f5f7"

cover_image                               : /aloud/assets/dark-theme-headphone-upon-books.webp                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.4

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#14261e"

link_color                                : "#666666"

app_title_color                           : "#f5f5f7"
app_price_color                           : "#f5f5f7"
app_description_color                     : "#f5f5f7"

feature_title_color                       : "#f5f5f7"
feature_text_color                        : "#e6e6e6"

feature_icons_foreground_color            : "#cef47e"
feature_icons_background_color            : "#486758"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#e6e6e6"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
